import math
import pandas as pd

from etl.readme_prediction_section import prediction_section_lines

def _fmt(x):
    try:
        if x is None or (isinstance(x, float) and math.isnan(x)):
            return "NA"
        return str(round(float(x), 2))
    except Exception:
        return "NA"

def update_readme(readme_path, kpis_csv_path, prediction=None):
    df = pd.read_csv(kpis_csv_path)
    latest = df.iloc[0].to_dict() if not df.empty else {}
    lines = []
    lines.append("# City Conditions ETL Pipeline\n\n")
    lines.append("A fully automated end-to-end ETL pipeline that pulls daily weather and air quality data for **Toronto, Canada**, loads it into a DuckDB analytics warehouse, and publishes KPI reports and charts updated every day via GitHub Actions.\n\n")
    lines.append("---\n\n")
    lines.append("## Data Sources\n\n")
    lines.append("All data is pulled from **[Open-Meteo](https://open-meteo.com/)** — a free, open-source weather and air quality API requiring no API key.\n\n")
    lines.append("| Source | API | Data Collected |\n")
    lines.append("|---|---|---|\n")
    lines.append("| Weather | [Open-Meteo Forecast API](https://api.open-meteo.com/v1/forecast) | Temperature (C), Precipitation (mm), Wind Speed (km/h) |\n")
    lines.append("| Air Quality | [Open-Meteo Air Quality API](https://air-quality-api.open-meteo.com/v1/air-quality) | PM2.5, PM10, NO2, Ozone |\n\n")
    lines.append("---\n\n")
    if latest:
        lines.append("## Latest KPI Snapshot\n\n")
        lines.append(f"- Date: **{latest.get('day')}**\n")
        lines.append(f"- Avg Temp (C): **{_fmt(latest.get('avg_temp_c'))}**\n")
        lines.append(f"- Max Temp (C): **{_fmt(latest.get('max_temp_c'))}**\n")
        lines.append(f"- Total Precip (mm): **{_fmt(latest.get('total_precip_mm'))}**\n")
        lines.append(f"- Avg Wind (km/h): **{_fmt(latest.get('avg_windspeed_kmh'))}**\n")
        lines.append(f"- Max Wind (km/h): **{_fmt(latest.get('max_windspeed_kmh'))}**\n")
        if "pm25_avg" in latest:
            lines.append(f"- PM2.5 Avg (ug/m3): **{_fmt(latest.get('pm25_avg'))}**\n")
            lines.append(f"- PM2.5 Peak (ug/m3): **{_fmt(latest.get('pm25_peak'))}**\n")
        lines.append("\n")
    lines.append("---\n\n")
    # --- model forecast + accuracy ---
    lines.extend(prediction_section_lines(prediction))

    lines.append("## Charts (auto-updated daily)\n\n")
    lines.append("### Weather\n\n")
    lines.append("- **Average Temperature (C):** daily mean temperature\n\n")
    lines.append("![Average Temperature (30d)](reports/charts/avg_temp_30d.png)\n\n")
    lines.append("- **Total Precipitation (mm):** total precipitation per day\n\n")
    lines.append("![Daily Precipitation (30d)](reports/charts/precip_30d.png)\n\n")
    lines.append("### Air Quality\n\n")
    lines.append("- **PM2.5 (ug/m3):** daily average fine particulate concentration (smaller = cleaner air)\n\n")
    lines.append("![PM2.5 Average (30d)](reports/charts/pm25_avg_30d.png)\n\n")
    lines.append("---\n\n")
    lines.append("## How It Works\n\n")
    lines.append("| Step | What happens |\n")
    lines.append("|---|---|\n")
    lines.append("| Extract | Pulls 7 days of hourly weather and air quality from Open-Meteo (observations only — `forecast_days=0`, so the API's own forecast never enters the observation tables) |\n")
    lines.append("| Transform | Cleans and validates: parses timestamps, nulls physically impossible values, deduplicates |\n")
    lines.append("| Load | Upserts into a DuckDB warehouse, keyed on (location_id, ts) so re-runs are idempotent |\n")
    lines.append("| History | Appends observed daily aggregates to `data/history/daily_observations.csv` — the durable record the model trains on |\n")
    lines.append("| Predict | Fits a RidgeCV model on lagged daily features, forecasts the next day, and scores every past forecast walk-forward |\n")
    lines.append("| Report | Generates KPI CSV, 30-day charts, forecast charts, and rewrites this README |\n")
    lines.append("| Log | Appends a row to reports/run_log.csv |\n\n")
    lines.append("---\n\n")
    lines.append("## Tech Stack\n\n")
    lines.append("| Technology | Purpose |\n")
    lines.append("|---|---|\n")
    lines.append("| Python | ETL scripting |\n")
    lines.append("| DuckDB | Analytics warehouse |\n")
    lines.append("| pandas | Data transformation |\n")
    lines.append("| requests | API extraction |\n")
    lines.append("| matplotlib | Chart generation |\n")
    lines.append("| scikit-learn | Forecasting model (RidgeCV) and validation |\n")
    lines.append("| pytest | Test suite |\n")
    lines.append("| GitHub Actions | Daily automation and CI |\n\n")
    lines.append("---\n\n")
    lines.append("## Outputs\n\n")
    lines.append("- `data/history/daily_observations.csv` — **the durable observation record.** Append-only, committed on every run, and what the forecasting model trains on\n")
    lines.append("- `warehouse/city_conditions.duckdb` — DuckDB warehouse, rebuilt from the API's rolling window each run (a derived artifact, not the system of record)\n")
    lines.append("- `reports/latest_kpis.csv` — most recent daily KPI snapshot\n")
    lines.append("- `reports/predictions.csv` — every forecast ever published, with the raw model output and whether sanity bounds were applied\n")
    lines.append("- `reports/prediction_backtest.csv` — per-day walk-forward scores: prediction, actual, and baseline\n")
    lines.append("- `reports/prediction_metrics.csv` — MAE / RMSE / skill history over time\n")
    lines.append("- `reports/run_log.csv` — log of every pipeline run\n")
    lines.append("- `reports/charts/*.png` — auto-generated 30-day charts\n\n")
    lines.append("---\n\n")
    lines.append("## Tests\n\n")
    lines.append("```bash\n")
    lines.append("pip install -r requirements-dev.txt\n")
    lines.append("pytest -q\n")
    lines.append("```\n\n")
    lines.append("The suite covers transform invariants, the no-leakage-across-calendar-gaps property of the feature builder, and regression tests for both extrapolation guards — including the literal 40 °C forecast this pipeline once published.\n\n")
    lines.append("---\n\n")
    lines.append("## How to Run Locally\n\n")
    lines.append("```bash\n")
    lines.append("git clone https://github.com/Data-Netrunner/City-Conditions-ETL-Pipeline.git\n")
    lines.append("cd City-Conditions-ETL-Pipeline\n")
    lines.append("pip install -r requirements.txt\n")
    lines.append("python etl/run_weather_pipeline.py\n")
    lines.append("```\n\n")
    lines.append("No API keys or paid services required.\n\n")
    lines.append("---\n\n")
    lines.append("*Built by Andre Felix - Data updated daily via GitHub Actions*\n")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.writelines(lines)
